-- Migration number: 0000 generated by teenybase on 2026-07-14T01:52:21.584Z. Do not modify this file.

CREATE TABLE users (
	id TEXT PRIMARY KEY NOT NULL, 
	github_id TEXT UNIQUE NOT NULL, 
	login TEXT NOT NULL, 
	avatar TEXT, 
	access_token TEXT NOT NULL, 
	default_environment TEXT NOT NULL DEFAULT "", 
	created_at TIMESTAMP NOT NULL, 
	updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_users_github_id ON users (github_id);
CREATE INDEX idx_users_login ON users (login);