-- Migration number: 0001 generated by teenybase on 2026-07-14T01:52:21.584Z. Do not modify this file.

CREATE TABLE repo_sets (
	id TEXT PRIMARY KEY NOT NULL, 
	user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, 
	name TEXT NOT NULL, 
	monorepo_full_name TEXT NOT NULL, 
	environment_name TEXT NOT NULL DEFAULT "", 
	members TEXT NOT NULL, 
	created_at TIMESTAMP NOT NULL, 
	updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_repo_sets_user_id ON repo_sets (user_id);
CREATE INDEX idx_repo_sets_monorepo_full_name ON repo_sets (monorepo_full_name);