-- Migration number: 0002 generated by teenybase on 2026-07-14T01:52:21.584Z. Do not modify this file.

CREATE TABLE launches (
	id TEXT PRIMARY KEY NOT NULL, 
	user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, 
	repo_set_id TEXT NOT NULL REFERENCES repo_sets(id) ON DELETE CASCADE, 
	vendor TEXT NOT NULL CHECK(vendor IN ('claude', 'codex')), 
	variant TEXT NOT NULL DEFAULT "default" CHECK(variant IN ('default', 'power')), 
	prompt TEXT NOT NULL, 
	deep_link TEXT NOT NULL, 
	created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_launches_user_id ON launches (user_id);
CREATE INDEX idx_launches_repo_set_id ON launches (repo_set_id);
CREATE INDEX idx_launches_created_at ON launches (created_at);