import { Validator } from "@cfworker/json-schema";
import type { GrantChange, ProposeGrantChangesResponse, WorkspaceView } from "@blitzos/schema";
import { beforeEach, describe, expect, it } from "vitest";
import {
  appRequest,
  harness,
  operatorSession,
  resetDatabase,
  workspacePhoneHomeUrl,
} from "./helpers.js";
import agentApiJson from "../../schema/openapi/agent-api.json?raw";

// The response half of the agent API conformance gate (plans/ORG-CREDENTIALS.md
// §4): each /agent/* route is driven through the real app, and what it answers
// is validated against the schema the generated document promises for that
// route and status. The schemas are strict (`additionalProperties: false`), so
// a field the server adds without a type change fails here, and a type change
// without regeneration fails test/agent-api-generate.test.mjs. Between the two,
// what GET /agent/api says is what the routes do.
//
// The last case demands that every documented success response was exercised
// above it, so a new route cannot be documented without being replayed.

const COMPONENTS_PREFIX = "#/components/schemas/";

interface MediaType { schema?: { $ref: string } }
interface ResponseObject { content: Record<string, MediaType> }
interface OperationObject { responses: Record<string, ResponseObject> }
interface AgentApiDocument {
  paths: Record<string, Record<string, OperationObject>>;
  components: { schemas: Record<string, unknown> };
}

// SAFETY: the artifact is generated by scripts/generate-agent-api.mjs, whose
// output shape is fixed there; test/agent-api-generate.test.mjs pins the bytes
// to that generator.
const document = JSON.parse(agentApiJson) as AgentApiDocument;

/** The validator resolves `#/$defs/…`, so the components are re-homed there
 * — the one transformation between the document and what validates against
 * it. Fresh per call: the validator annotates the schema objects it walks. */
function validatorFor(typeName: string): Validator {
  const schemas = JSON.parse(
    JSON.stringify(document.components.schemas).replaceAll(`"${COMPONENTS_PREFIX}`, '"#/$defs/'),
  );
  return new Validator({ $ref: `#/$defs/${typeName}`, $defs: schemas }, "2020-12", false);
}

const template = (routePath: string): string => routePath.replaceAll(/:([^/]+)/gu, "{$1}");

const exercised = new Set<string>();

/** Asserts the response is the status the caller expects and that its body
 * matches the schema the document names for that route and status. */
async function conforms(
  response: Response,
  method: string,
  routePath: string,
  status: number,
): Promise<unknown> {
  const operation = document.paths[template(routePath)]?.[method.toLowerCase()];
  const documented = operation?.responses[String(status)];
  expect(documented, `${method} ${routePath} does not document ${String(status)}`).toBeDefined();
  const ref = documented?.content["application/json"]?.schema?.$ref;
  expect(ref, `${method} ${routePath} ${String(status)} names no schema`).toBeDefined();
  expect(response.status).toBe(status);
  const body: unknown = await response.json();
  const typeName = String(ref).slice(COMPONENTS_PREFIX.length);
  const result = validatorFor(typeName).validate(body);
  expect(result.errors, `${method} ${routePath} ${String(status)} is not a ${typeName}`).toEqual([]);
  exercised.add(`${method} ${template(routePath)} ${String(status)}`);
  return body;
}

type Harness = ReturnType<typeof harness>;

function json(body: object, method = "POST", token?: string): RequestInit {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (token !== undefined) headers.Authorization = `Bearer ${token}`;
  return { method, headers, body: JSON.stringify(body) };
}

const bearer = (token: string, method = "GET"): RequestInit => ({
  method,
  headers: { Authorization: `Bearer ${token}` },
});

async function createWorkspaceWith(
  app: Harness["app"],
  cookie: string,
  body: Record<string, unknown> = {},
): Promise<WorkspaceView> {
  const created = await appRequest(app, "/workspaces", {
    ...json({ machineTypeId: "small", ...body }),
    headers: { Cookie: cookie, "Content-Type": "application/json" },
  });
  expect(created.status).toBe(201);
  return (await created.json<{ workspace: WorkspaceView }>()).workspace;
}

/** One member's machine credential, through the machine's own phone-home. */
async function machineToken(
  app: Harness["app"],
  providers: Harness["providers"],
  workspaceId: string,
): Promise<string> {
  const url = await workspacePhoneHomeUrl(providers, workspaceId);
  const ready = await appRequest(app, new URL(url).pathname, json({
    pub_key_ed25519: "ssh-ed25519 AAAAhost",
  }));
  expect(ready.status).toBe(200);
  return (await ready.json<{ access_token: string }>()).access_token;
}

async function storeOrgCredential(
  app: Harness["app"],
  cookie: string,
  body: Record<string, unknown>,
): Promise<void> {
  const stored = await appRequest(app, "/orgs/self/credentials", {
    ...json(body, "PUT"),
    headers: { Cookie: cookie, "Content-Type": "application/json" },
  });
  expect(stored.status).toBe(201);
}

describe("agent API conformance (plans/ORG-CREDENTIALS.md §4)", () => {
  beforeEach(resetDatabase);

  it("serves the generated document verbatim to a machine, and refuses anyone else", async () => {
    const { app, providers } = harness();
    const cookie = await operatorSession(app);
    const workspace = await createWorkspaceWith(app, cookie);
    const token = await machineToken(app, providers, workspace.id);

    const served = await appRequest(app, "/agent/api", bearer(token));
    expect(served.status).toBe(200);
    expect(served.headers.get("Content-Type")).toBe("application/json; charset=utf-8");
    expect(await served.text()).toBe(agentApiJson);
    exercised.add("GET /agent/api 200");

    await conforms(await appRequest(app, "/agent/api"), "GET", "/agent/api", 401);
  });

  it("lists, resolves both tiers, and files the documented 404", async () => {
    const { app, providers } = harness();
    const cookie = await operatorSession(app);
    expect((await appRequest(app, "/connections/grants/linear", {
      ...json({ manifestId: "linear", token: "lin_api_test-only-personal-key" }, "PUT"),
      headers: { Cookie: cookie, "Content-Type": "application/json" },
    })).status).toBe(204);
    const workspace = await createWorkspaceWith(app, cookie, {
      manifest: { integrations: { linear: {} } },
    });
    await storeOrgCredential(app, cookie, {
      name: "STRIPE_API_KEY",
      value: "sk_live_value",
      comment: "billing key",
    });
    const token = await machineToken(app, providers, workspace.id);

    const listed = await conforms(
      await appRequest(app, "/agent/credentials", bearer(token)),
      "GET",
      "/agent/credentials",
      200,
    );
    expect(listed).toMatchObject({
      credentials: [{ name: "STRIPE_API_KEY", scope: "org" }, { name: "linear", scope: "connection" }],
    });

    const tokenRoute = "/agent/credentials/:name/token";
    const org = await conforms(
      await appRequest(app, "/agent/credentials/STRIPE_API_KEY/token", bearer(token, "POST")),
      "POST",
      tokenRoute,
      200,
    );
    expect(org).toMatchObject({ scope: "org", token: "sk_live_value" });
    const connection = await conforms(
      await appRequest(app, "/agent/credentials/linear/token", bearer(token, "POST")),
      "POST",
      tokenRoute,
      200,
    );
    expect(connection).toMatchObject({ scope: "connection", name: "linear" });
    await conforms(
      await appRequest(app, "/agent/credentials/github/token", bearer(token, "POST")),
      "POST",
      tokenRoute,
      404,
    );
  });

  it("creates, rotates and imports through the write doors", async () => {
    const { app, providers } = harness();
    const cookie = await operatorSession(app);
    const workspace = await createWorkspaceWith(app, cookie);
    const token = await machineToken(app, providers, workspace.id);

    const putRoute = "/agent/credentials/:name";
    const created = await conforms(
      await appRequest(app, "/agent/credentials/NEW_KEY", json({
        value: "first",
        comment: "test-mode key",
      }, "PUT", token)),
      "PUT",
      putRoute,
      201,
    );
    expect(created).toMatchObject({ credential: { name: "NEW_KEY", comment: "test-mode key" } });
    await conforms(
      await appRequest(app, "/agent/credentials/NEW_KEY", json({ value: "second" }, "PUT", token)),
      "PUT",
      putRoute,
      200,
    );

    const imported = await conforms(
      await appRequest(app, "/agent/credentials/dotenv", json({
        text: "A_KEY=one\nNEW_KEY=second\n\n=bad\n",
      }, "POST", token)),
      "POST",
      "/agent/credentials/dotenv",
      200,
    );
    expect(imported).toMatchObject({ linesRead: 4 });
  });

  it("proposes grant changes and polls them to approval", async () => {
    const { app, providers } = harness();
    const cookie = await operatorSession(app);
    const workspace = await createWorkspaceWith(app, cookie);
    await storeOrgCredential(app, cookie, { name: "SHARED_KEY", value: "shared" });
    const token = await machineToken(app, providers, workspace.id);
    const changes: GrantChange[] = [{
      name: "SHARED_KEY",
      action: "add",
      subjectKind: "org",
      subjectId: null,
      access: "read",
    }];

    const filed = await conforms(
      await appRequest(app, "/agent/credentials/grant-proposals", json({
        changes,
        reason: "the whole org reads it",
      }, "POST", token)),
      "POST",
      "/agent/credentials/grant-proposals",
      201,
    );
    // SAFETY: conforms() validated the body against ProposeGrantChangesResponse.
    const { id } = filed as ProposeGrantChangesResponse;

    const pollRoute = "/agent/grant-proposals/:id";
    const pending = await conforms(
      await appRequest(app, `/agent/grant-proposals/${id}`, bearer(token)),
      "GET",
      pollRoute,
      200,
    );
    expect(pending).toMatchObject({ id, state: "pending", applied: null });

    const resolved = await appRequest(app, `/orgs/self/grant-proposals/${id}/resolve`, {
      ...json({ approve: true, changes }),
      headers: { Cookie: cookie, "Content-Type": "application/json" },
    });
    expect(resolved.status).toBe(200);
    const approved = await conforms(
      await appRequest(app, `/agent/grant-proposals/${id}`, bearer(token)),
      "GET",
      pollRoute,
      200,
    );
    expect(approved).toMatchObject({ id, state: "approved", applied: changes });
  });

  it("exercised every success response the document promises", () => {
    const promised = Object.entries(document.paths)
      .flatMap(([path, item]) => Object.entries(item)
        .flatMap(([method, operation]) => Object.keys(operation.responses)
          .filter((status) => status.startsWith("2"))
          .map((status) => `${method.toUpperCase()} ${path} ${status}`)))
      .sort();
    expect(promised.length).toBeGreaterThan(0);
    expect(promised.filter((entry) => !exercised.has(entry))).toEqual([]);
  });
});
