import { describe, expect, it } from "vitest";
import { AGENT_ROUTES, installControlPlaneRoutes } from "../core/index.js";
import type { CoreHandler, CoreRouter } from "../core/runtime.js";
import agentApiJson from "../../schema/openapi/agent-api.json?raw";

// The bidirectional route-coverage gate (plans/ORG-CREDENTIALS.md §4): every
// /agent/* route the control plane registers is in the generated document,
// and every path+method the document lists is registered. The manifest the
// generator reads sits between them, so the three are held equal at once —
// a route added to core without a manifest entry, a manifest entry without a
// route, and a document regenerated from either drift all fail here.

const METHODS = ["all", "get", "post", "put", "patch", "delete"] as const;

/** A CoreRouter that records registrations instead of serving them. The
 * runtime factory is never called during registration, so it need not exist:
 * this is the whole accessor the router type needs to be enumerable. */
class RecordingRouter implements CoreRouter {
  readonly registered: string[] = [];

  private record(method: string, path: string): CoreRouter {
    this.registered.push(`${method.toUpperCase()} ${path}`);
    return this;
  }

  all(path: string, _handler: CoreHandler): CoreRouter { return this.record("all", path); }
  get(path: string, _handler: CoreHandler): CoreRouter { return this.record("get", path); }
  post(path: string, _handler: CoreHandler): CoreRouter { return this.record("post", path); }
  patch(path: string, _handler: CoreHandler): CoreRouter { return this.record("patch", path); }
  put(path: string, _handler: CoreHandler): CoreRouter { return this.record("put", path); }
  delete(path: string, _handler: CoreHandler): CoreRouter { return this.record("delete", path); }
  notFound(_handler: CoreHandler): CoreRouter { return this; }
  onError(): CoreRouter { return this; }
}

function registeredAgentRoutes(): string[] {
  const router = new RecordingRouter();
  installControlPlaneRoutes(router, () => {
    throw new Error("route registration must not build a runtime");
  });
  return router.registered.filter((entry) => entry.split(" ")[1]?.startsWith("/agent/")).sort();
}

interface DocumentPaths {
  paths: Record<string, Partial<Record<(typeof METHODS)[number], unknown>>>;
}

/** The document's routes, in the router's spelling: `{name}` back to `:name`. */
function documentedAgentRoutes(): string[] {
  // SAFETY: the artifact is generated by scripts/generate-agent-api.mjs, whose
  // output shape is fixed there; test/agent-api-generate.test.mjs pins the
  // bytes to that generator.
  const document = JSON.parse(agentApiJson) as DocumentPaths;
  return Object.entries(document.paths)
    .flatMap(([template, item]) =>
      METHODS
        .filter((method) => item[method] !== undefined)
        .map((method) => `${method.toUpperCase()} ${template.replaceAll(/\{([^}]+)\}/gu, ":$1")}`))
    .sort();
}

describe("agent API route coverage (plans/ORG-CREDENTIALS.md §4)", () => {
  it("documents every registered /agent/* route, and registers every documented one", () => {
    const registered = registeredAgentRoutes();
    expect(registered.length).toBeGreaterThan(0);
    expect(documentedAgentRoutes()).toEqual(registered);
  });

  it("keeps the manifest the generator reads equal to the router", () => {
    const listed = AGENT_ROUTES.map((route) => `${route.method} ${route.path}`).sort();
    expect(new Set(listed).size, "a route is listed twice in AGENT_ROUTES").toBe(listed.length);
    expect(listed).toEqual(registeredAgentRoutes());
  });
});
