import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { boxImageDecision, IMAGE_PATHS } from "../scripts/check-box-image.mjs";
import {
  COMPARED_LISTS,
  configKeyPaths,
  configRepairPlan,
  missingConfigKeys,
  missingListEntries,
} from "../scripts/config-drift.mjs";
import {
  hasRunWorkerFirst,
  runWorkerFirstPatch,
  runWorkerFirstRemoval,
} from "../scripts/deploy-helpers.mjs";
import { isNonEmptyString, isTable } from "../scripts/lib/values.mjs";
import {
  coreRoutePaths,
  deriveRunWorkerFirst,
  devProxyPatterns,
  managedApiExactPaths,
  managedApiPrefixes,
  routingPlan,
  runWorkerFirstEntries,
} from "../scripts/lib/worker-first-routes.mjs";
import { withGeneratedRunWorkerFirst } from "../scripts/sync-worker-first-routes.mjs";
import {
  CONFIG_PATH,
  deploymentVersionIds,
  REPO_ROOT,
  rollbackTarget,
} from "../scripts/rollback.mjs";

const fixturesDirectory = fileURLToPath(
  new URL("../../schema/fixtures/version/", import.meta.url),
);
const packageDirectory = fileURLToPath(new URL("..", import.meta.url));

// --- value decoders ---------------------------------------------------------

test("isTable accepts a table and rejects what typeof gets wrong", () => {
  assert.equal(isTable({ a: 1 }), true);
  // The three cases `typeof x === "object"` answers true for, wrongly.
  assert.equal(isTable(null), false);
  assert.equal(isTable([1, 2]), false);
  assert.equal(isTable(new Date(0)), false);
  assert.equal(isTable(undefined), false);
  assert.equal(isTable("x"), false);
  assert.equal(isTable(1), false);
});

test("isNonEmptyString accepts a primitive string only", () => {
  assert.equal(isNonEmptyString("abc"), true);
  assert.equal(isNonEmptyString(""), false);
  assert.equal(isNonEmptyString(null), false);
  assert.equal(isNonEmptyString(undefined), false);
  assert.equal(isNonEmptyString(1), false);
  assert.equal(isNonEmptyString(["a"]), false);
  // A boxed String is not a string value, and must not pass as one.
  assert.equal(isNonEmptyString(new String("abc")), false);
});

// --- config drift -----------------------------------------------------------

test("configKeyPaths flattens tables and arrays of tables", () => {
  const paths = configKeyPaths({
    name: "w",
    vars: { APP_URL: "" },
    d1_databases: [{ binding: "DB", database_id: "x" }],
  });
  assert.ok(paths.has("name"));
  assert.ok(paths.has("vars.APP_URL"));
  assert.ok(paths.has("d1_databases[].binding"));
});

test("missingConfigKeys names a key the example gained", () => {
  const example = '[vars]\nAPP_URL = ""\nGIT_COMMIT_SHA = ""\n';
  const config = '[vars]\nAPP_URL = "https://x"\n';
  assert.deepEqual(missingConfigKeys(example, config), ["vars.GIT_COMMIT_SHA"]);
});

test("missingConfigKeys ignores values and extra keys", () => {
  const example = '[vars]\nAPP_URL = ""\n';
  const config = '[vars]\nAPP_URL = "https://x"\nEXTRA = "1"\n';
  assert.deepEqual(missingConfigKeys(example, config), []);
});

test("a config generated from the example carries every key", () => {
  // ensure-wrangler-config.mjs re-serializes the example, so a fresh clone must
  // never trip the drift gate.
  const example = readFileSync(path.join(packageDirectory, "wrangler.toml.example"), "utf8");
  assert.deepEqual(missingConfigKeys(example, example), []);
});

test("the example declares GIT_COMMIT_SHA and routes /version to the worker", () => {
  const example = readFileSync(path.join(packageDirectory, "wrangler.toml.example"), "utf8");
  assert.match(example, /GIT_COMMIT_SHA/u);
  assert.match(example, /"\/version"/u);
});

// --- routing list drift -----------------------------------------------------

// assets.run_worker_first is generated by the deploy now, so it is no longer
// compared. It used to be, because the key-path check passed a config that had
// the key and not the entry — /version reached wrangler.toml.example and
// neither deployment, and both passed. Comparing it today would fail the deploy
// on drift the same deploy repairs three steps later.
const EXAMPLE_ASSETS = [
  "[assets]",
  'run_worker_first = [ "/sessions*", "/version", "/api/*" ]',
  "",
  "[triggers]",
  'crons = [ "*/5 * * * *", "0 3 * * *" ]',
  "",
].join("\n");

test("a config that routes nothing to the worker is no longer drift: the deploy writes the list", () => {
  const config = [
    "[assets]",
    'run_worker_first = [ ]',
    "",
    "[triggers]",
    'crons = [ "*/5 * * * *", "0 3 * * *" ]',
    "",
  ].join("\n");
  assert.deepEqual(missingListEntries(EXAMPLE_ASSETS, config), []);
});

test("missingConfigKeys ignores the generated key even when the config lacks it", () => {
  const config = ['[assets]', 'directory = "d"', "", "[triggers]", 'crons = [ ]', ""].join("\n");
  const example = ['[assets]', 'directory = "d"', 'run_worker_first = [ "/version" ]', "", "[triggers]", 'crons = [ ]', ""].join("\n");
  assert.deepEqual(missingConfigKeys(example, config), []);
});

test("missingListEntries names a missing cron", () => {
  const config = [
    "[assets]",
    'run_worker_first = [ "/sessions*", "/version", "/api/*" ]',
    "",
    "[triggers]",
    'crons = [ "*/5 * * * *" ]',
    "",
  ].join("\n");
  assert.deepEqual(missingListEntries(EXAMPLE_ASSETS, config), [
    { path: "triggers.crons", missing: ["0 3 * * *"] },
  ]);
});

test("a config may run more crons than the example, and that is not drift", () => {
  const config = [
    "[triggers]",
    'crons = [ "*/5 * * * *", "0 3 * * *", "0 4 * * *" ]',
    "",
  ].join("\n");
  assert.deepEqual(missingListEntries(EXAMPLE_ASSETS, config), []);
});

test("an absent table reports every entry rather than passing quietly", () => {
  assert.deepEqual(missingListEntries(EXAMPLE_ASSETS, 'name = "w"\n'), [
    { path: "triggers.crons", missing: ["*/5 * * * *", "0 3 * * *"] },
  ]);
});

test("the example agrees with itself on every compared list", () => {
  const example = readFileSync(path.join(packageDirectory, "wrangler.toml.example"), "utf8");
  assert.deepEqual(missingListEntries(example, example), []);
});

test("COMPARED_LISTS holds the one list still compared", () => {
  assert.deepEqual(COMPARED_LISTS.map((entry) => entry.join(".")), ["triggers.crons"]);
});

// --- config repair ----------------------------------------------------------

// The deploy fills a stale config in from the example instead of refusing.
// Before this, a new var meant re-pasting CANARY_WRANGLER_TOML and
// PROD_WRANGLER_TOML by hand; it happened twice in one evening.
const REPAIR_EXAMPLE = [
  'name = "w"',
  "",
  "[vars]",
  'APP_URL = ""',
  'GIT_COMMIT_SHA = ""',
  'MICROVM_HOSTS = "[]"',
  "",
  "[assets]",
  'directory = "../webapp/dist"',
  'run_worker_first = [ "/version" ]',
  "",
  "[triggers]",
  'crons = [ "*/5 * * * *", "0 3 * * *" ]',
  "",
  "[observability]",
  "enabled = true",
  "",
].join("\n");

test("a var the example gained is filled in from the example, not demanded of the operator", () => {
  const config = [
    'name = "w"',
    "",
    "[vars]",
    'APP_URL = "https://deployed.example"',
    'MICROVM_HOSTS = "[]"',
    "",
    "[assets]",
    'directory = "../webapp/dist"',
    "",
    "[triggers]",
    'crons = [ "*/5 * * * *", "0 3 * * *" ]',
    "",
    "[observability]",
    "enabled = true",
    "",
  ].join("\n");
  const plan = configRepairPlan(REPAIR_EXAMPLE, config);
  assert.deepEqual(plan.unfillable, []);
  assert.deepEqual(plan.filled, [{ path: "vars.GIT_COMMIT_SHA", value: "" }]);
  assert.deepEqual(plan.patches, [{ vars: { GIT_COMMIT_SHA: "" } }]);
});

test("the repair never overwrites a value the deployment already set", () => {
  const plan = configRepairPlan(REPAIR_EXAMPLE, REPAIR_EXAMPLE.replace('APP_URL = ""', 'APP_URL = "https://deployed.example"'));
  assert.deepEqual(plan.filled, []);
  assert.deepEqual(plan.patches, []);
});

test("a whole missing table is filled in, values and all", () => {
  const config = ['name = "w"', "", "[vars]", 'APP_URL = ""', 'GIT_COMMIT_SHA = ""', 'MICROVM_HOSTS = "[]"', "", "[assets]", 'directory = "../webapp/dist"', "", "[triggers]", 'crons = [ "*/5 * * * *", "0 3 * * *" ]', ""].join("\n");
  const plan = configRepairPlan(REPAIR_EXAMPLE, config);
  assert.deepEqual(plan.filled, [{ path: "observability.enabled", value: true }]);
  assert.deepEqual(plan.patches, [{ observability: { enabled: true } }]);
});

test("the generated route list is never filled in: the deploy writes it", () => {
  const config = REPAIR_EXAMPLE.replace('run_worker_first = [ "/version" ]\n', "");
  const plan = configRepairPlan(REPAIR_EXAMPLE, config);
  assert.deepEqual(plan.filled, []);
  assert.deepEqual(plan.patches, []);
});

test("a missing cron is repaired as a union, so a deployment keeps its own", () => {
  const config = REPAIR_EXAMPLE.replace(
    'crons = [ "*/5 * * * *", "0 3 * * *" ]',
    'crons = [ "*/5 * * * *", "0 9 * * *" ]',
  );
  const plan = configRepairPlan(REPAIR_EXAMPLE, config);
  assert.deepEqual(plan.filled, [{ path: "triggers.crons[]", value: "0 3 * * *" }]);
  // Removed first, then written whole: wrangler patches an array element by
  // element and would otherwise leave the old tail in place.
  assert.deepEqual(plan.patches, [
    { triggers: { crons: undefined } },
    { triggers: { crons: ["*/5 * * * *", "0 9 * * *", "0 3 * * *"] } },
  ]);
});

test("a placeholder the operator alone can replace stops the deploy", () => {
  const example = ['name = "w"', "", "[vars]", 'ZONE = "<your zone id>"', ""].join("\n");
  const plan = configRepairPlan(example, 'name = "w"\n');
  assert.deepEqual(plan.filled, []);
  assert.equal(plan.unfillable.length, 1);
  assert.equal(plan.unfillable[0].path, "vars.ZONE");
  assert.match(plan.unfillable[0].reason, /placeholder/u);
});

test("the real example needs no repair against a config generated from it", () => {
  const example = readFileSync(path.join(packageDirectory, "wrangler.toml.example"), "utf8");
  const plan = configRepairPlan(example, example);
  assert.deepEqual(plan.filled, []);
  assert.deepEqual(plan.unfillable, []);
});

// --- worker-first route derivation ------------------------------------------

// One source of truth: core's own route registrations. Everything that used to
// hold a hand-written copy — wrangler.toml.example, the two deployment secrets,
// the managed worker, the vite dev proxy — asks the generator instead.

test("a segment with children gets a subtree entry, one without gets an exact entry", () => {
  const entries = runWorkerFirstEntries(["/me", "/members", "/members/:id", "/auth/google/start"]);
  assert.deepEqual(entries, ["/auth/*", "/me", "/members", "/members/*"]);
});

test("the root is an exact entry and never a prefix", () => {
  // "/*" would route every asset request — the SPA bundle included — through
  // the Worker, which is the failure this whole generator exists to prevent.
  const entries = runWorkerFirstEntries(["/", "/version"]);
  assert.deepEqual(entries, ["/", "/version"]);
  assert.equal(entries.includes("/*"), false);
  assert.equal(routingPlan(["/"]).root, true);
  assert.deepEqual(routingPlan(["/"]).segments, []);
});

test("the managed worker matches the root exactly, because it matches prefixes with startsWith", () => {
  assert.deepEqual(managedApiExactPaths(["/", "/version", "/members/:id"]), ["/", "/version"]);
  assert.deepEqual(managedApiPrefixes(["/", "/version", "/members/:id"]), ["/members/"]);
});

test("dev-proxy patterns are anchored, so a route never claims a name that starts like it", () => {
  const patterns = devProxyPatterns(["/", "/me", "/members/:id"]);
  // The root is absent on purpose: vite serves the SPA at "/" in dev.
  assert.deepEqual(patterns, ["^/me(?:$|[/?])", "^/members/"]);
  const matches = (url) => patterns.some((pattern) => new RegExp(pattern, "u").test(url));
  assert.equal(matches("/me"), true);
  assert.equal(matches("/me?x=1"), true);
  assert.equal(matches("/members/self"), true);
  assert.equal(matches("/menu"), false);
  assert.equal(matches("/members-directory"), false);
  assert.equal(matches("/index.html"), false);
  assert.equal(matches("/"), false);
});

test("a route registered with a computed path is named, not silently dropped", () => {
  const { paths, nonLiteral } = coreRoutePaths([
    { path: "core/a.ts", source: 'router.get("/ok", h);\nrouter.post(`/${dynamic}`, h);' },
  ]);
  assert.deepEqual(paths, ["/ok"]);
  assert.deepEqual(nonLiteral, [{ path: "core/a.ts", registrations: 2, literals: 1 }]);
});

test("router.all is scanned too, or /proxy leaves the list", () => {
  const { paths, nonLiteral } = coreRoutePaths([
    { path: "core/proxy.ts", source: 'router.all("/proxy/:leaseId/*", h);' },
  ]);
  assert.deepEqual(paths, ["/proxy/:leaseId/*"]);
  assert.deepEqual(nonLiteral, []);
});

test("the derived list claims a request to every route core registers today", () => {
  const entries = deriveRunWorkerFirst();
  const claims = (pathname) => entries.some((entry) => {
    const pattern = entry.split("*").map((literal) => literal.replaceAll(/[.+?^${}()|[\]\\]/gu, String.raw`\$&`)).join(".*");
    return new RegExp(`^${pattern}$`, "u").test(pathname);
  });
  for (const pathname of ["/version", "/me", "/sessions/switch-org", "/workspaces/abc/environment", "/proxy/lease/x", "/api/v1/health"]) {
    assert.equal(claims(pathname), true, pathname);
  }
  for (const pathname of ["/index.html", "/assets/index-abcd1234.js", "/members-directory", "/menu"]) {
    assert.equal(claims(pathname), false, pathname);
  }
});

test("wrangler.toml.example carries exactly what the generator produces", () => {
  const example = readFileSync(path.join(packageDirectory, "wrangler.toml.example"), "utf8");
  assert.equal(
    withGeneratedRunWorkerFirst(example, deriveRunWorkerFirst()),
    example,
    "run `npm run routes:sync -w packages/control-plane`",
  );
});

// --- the deploy's run_worker_first patch -------------------------------------

test("the patch replaces the array outright, removing it first", () => {
  assert.deepEqual(runWorkerFirstPatch(["/a", "/b"]), { assets: { run_worker_first: ["/a", "/b"] } });
  assert.deepEqual(runWorkerFirstRemoval(), { assets: { run_worker_first: undefined } });
  assert.equal(hasRunWorkerFirst({ assets: { run_worker_first: [] } }), true);
  assert.equal(hasRunWorkerFirst({ assets: { directory: "d" } }), false);
  assert.equal(hasRunWorkerFirst({}), false);
});

test("an empty derived list is refused rather than written", () => {
  // Writing one would hand every core route to the asset handler at once.
  assert.throws(() => runWorkerFirstPatch([]), /every core route would be served the SPA shell/u);
});

// --- box image decision -----------------------------------------------------

test("no image path changed means no rebuild", () => {
  const decision = boxImageDecision("abc1234", ["packages/webapp/src/App.tsx"]);
  assert.equal(decision.rebuild, false);
  assert.deepEqual(decision.paths, []);
});

test("a box change requires a rebuild", () => {
  const decision = boxImageDecision("abc1234", [
    "packages/box/actor/src/actor.ts",
    "packages/webapp/src/App.tsx",
  ]);
  assert.equal(decision.rebuild, true);
  assert.deepEqual(decision.paths, ["packages/box/actor/src/actor.ts"]);
});

test("a broker change requires a rebuild", () => {
  assert.equal(boxImageDecision("abc", ["packages/broker/main.go"]).rebuild, true);
});

test("a path that merely starts with an image path prefix does not count", () => {
  // "packages/boxes/..." is not "packages/box/...".
  assert.equal(boxImageDecision("abc", ["packages/boxes/thing.ts"]).rebuild, false);
});

test("IMAGE_PATHS names both image sources", () => {
  assert.deepEqual([...IMAGE_PATHS], ["packages/box", "packages/broker"]);
});

// --- the /version contract, consumer side -----------------------------------

test("every version fixture carries the fields the consumer reads", () => {
  for (const name of ["deployed.json", "unknown-commit.json", "fresh-database.json"]) {
    const body = JSON.parse(readFileSync(path.join(fixturesDirectory, name), "utf8"));
    assert.equal(typeof body.commit, "string", name);
    assert.notEqual(body.commit, "", name);
    assert.equal(typeof body.boxImageRef, "string", name);
    assert.ok(body.migration === null || typeof body.migration === "string", name);
  }
});

// --- rollback ---------------------------------------------------------------

const deployment = (createdOn, ...versionIds) => ({
  created_on: createdOn,
  versions: versionIds.map((id) => ({ version_id: id })),
});

// `npm run rollback -w packages/control-plane` runs with cwd set to the
// package, so a cwd-relative CONFIG_PATH resolved to
// packages/control-plane/packages/control-plane/wrangler.toml and the tool
// could not run at all. The unit tests covered only the pure functions, so
// nothing caught it.
test("the config path resolves against the repo root, not the caller's cwd", () => {
  const resolved = path.join(REPO_ROOT, CONFIG_PATH);
  assert.equal(resolved, path.join(packageDirectory, "wrangler.toml"));
  assert.equal(
    JSON.parse(readFileSync(path.join(REPO_ROOT, "package.json"), "utf8")).name,
    "blitz-core",
  );
});

test("deploymentVersionIds reads both version_id and id spellings", () => {
  assert.deepEqual(deploymentVersionIds({ versions: [{ version_id: "a" }, { id: "b" }] }), ["a", "b"]);
  assert.deepEqual(deploymentVersionIds({}), []);
  assert.deepEqual(deploymentVersionIds(null), []);
});

test("rollbackTarget picks the previous single-version deployment", () => {
  const { current, target } = rollbackTarget([
    deployment("2026-08-20T00:00:00Z", "old"),
    deployment("2026-08-25T00:00:00Z", "new"),
  ]);
  assert.equal(current, "new");
  assert.equal(target, "old");
});

test("rollbackTarget skips a deployment that served the same version again", () => {
  const { target } = rollbackTarget([
    deployment("2026-08-19T00:00:00Z", "older"),
    deployment("2026-08-20T00:00:00Z", "new"),
    deployment("2026-08-25T00:00:00Z", "new"),
  ]);
  assert.equal(target, "older");
});

test("rollbackTarget refuses to guess during a split", () => {
  assert.throws(
    () => rollbackTarget([deployment("2026-08-25T00:00:00Z", "a", "b")]),
    /serves 2 versions at once/u,
  );
});

test("rollbackTarget refuses when nothing earlier exists", () => {
  assert.throws(
    () => rollbackTarget([deployment("2026-08-25T00:00:00Z", "only")]),
    /nothing to roll back to/u,
  );
});

test("rollbackTarget rejects an empty list", () => {
  assert.throws(() => rollbackTarget([]), /no deployments/u);
});
