export function escapeHtml(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function formatTime(value) {
  if (!value) return ''
  const date = new Date(String(value).replace(' ', 'T') + (String(value).includes('Z') ? '' : 'Z'))
  if (Number.isNaN(date.getTime())) return String(value)
  return new Intl.DateTimeFormat('en', {month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit'}).format(date)
}

export const PRIVACY_LINE = 'We store your GitHub login, avatar, OAuth token, repo names and branches, and launch prompts. Your repository code is never stored on BlitzOS servers.'

export const GLOBAL_CSS = [
  '*{box-sizing:border-box}',
  ':root{color-scheme:light;--paper:#f2f1ec;--card:#fff;--ink:#1a1a18;--mut:#75756e;--dim:#a9a79e;--line:#c9c8c1;--accent:#ff4f00;--soft:#fff5ef;--ok:#1a9e50;--bad:#d1442b;--mono:"SF Mono",SFMono-Regular,ui-monospace,Menlo,Consolas,monospace;--sans:"Helvetica Neue",Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}',
  'html{min-height:100%;background:var(--paper)}',
  'body{min-height:100%;margin:0;color:var(--ink);font-family:var(--sans);line-height:1.45;background:radial-gradient(rgba(120,118,108,.16) 1px,transparent 1.2px) 0 0/22px 22px,var(--paper)}',
  'button,input,textarea,select{font:inherit}',
  'a{color:inherit}',
  '.shell{width:min(1180px,calc(100% - 36px));margin:0 auto;padding:20px 0 48px}',
  '.nav{display:flex;align-items:center;justify-content:space-between;gap:20px;min-height:42px;margin-bottom:38px}',
  '.nav-left,.nav-right{display:flex;align-items:center;gap:18px}',
  '.wordmark{font:800 13px var(--mono);letter-spacing:.08em;text-decoration:none;text-transform:lowercase}',
  '.nav-link,.micro-link{font:700 11px var(--mono);letter-spacing:.06em;text-transform:lowercase;color:var(--mut);text-decoration:none}',
  '.nav-link:hover,.micro-link:hover{color:var(--accent)}',
  '.account{display:flex;align-items:center;gap:9px;font:700 11px var(--mono);color:var(--mut)}',
  '.avatar{width:28px;height:28px;border-radius:50%;border:1px solid var(--line);background:var(--card)}',
  '.bare-form{display:inline;margin:0}',
  '.link-button{padding:0;border:0;background:none;color:var(--mut);font:700 11px var(--mono);cursor:pointer}',
  '.link-button:hover{color:var(--accent)}',
  '.micro{font:700 10.5px var(--mono);letter-spacing:.08em;text-transform:lowercase;color:var(--mut)}',
  '.status{display:inline-flex;align-items:center;gap:7px}',
  '.status:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--accent)}',
  '.hero{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(360px,.75fr);gap:36px;align-items:end}',
  '.hero h1{margin:0 0 16px;font-size:clamp(42px,5vw,70px);font-weight:420;letter-spacing:-.058em;line-height:.99}',
  '.hero h1 span{white-space:nowrap}',
  '.sub{margin:0;color:var(--mut);font-size:15.5px;max-width:470px}',
  '.ledger{position:relative;display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line);background:rgba(255,255,255,.35)}',
  '.tick{position:absolute;font:400 12px var(--mono);color:var(--dim);line-height:1}',
  '.tick.tl{top:-7px;left:-5px}.tick.tr{top:-7px;right:-5px}.tick.bl{bottom:-7px;left:-5px}.tick.br{bottom:-7px;right:-5px}',
  '.ledger .col{display:grid;grid-template-rows:auto auto 1fr auto}',
  '.ledger>.col:only-of-type{grid-column:1/-1}',
  '.ledger .col+.col{border-left:1px solid var(--line)}',
  '.ledger .cell{padding:12px 16px;border-top:1px solid var(--line)}',
  '.ledger .col .cell:first-child{border-top:0}',
  '.ledger .cell.copy{font-size:13.5px}',
  '.ledger .cell.facts{font:500 11.5px var(--mono);color:var(--mut)}',
  '.ledger .cell.facts div{padding:2px 0}',
  '.ledger .cell.facts div:before{content:"+ ";color:var(--accent)}',
  '.actions{display:flex;flex-wrap:wrap;gap:10px}',
  '.button{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 17px;border:1.5px solid var(--ink);border-radius:11px;background:var(--ink);color:#fff;font-weight:750;font-size:14px;text-decoration:none;cursor:pointer}',
  '.button:hover{background:#33332f}',
  '.button.accent{border-color:var(--accent);background:var(--accent)}',
  '.button.accent:hover{background:#e64700}',
  '.button.secondary{background:transparent;color:var(--ink);border-color:var(--line)}',
  '.button.secondary:hover{border-color:var(--ink);background:rgba(255,255,255,.45)}',
  '.button.small{min-height:34px;padding:0 12px;border-radius:9px;font-size:12px}',
  '.button.danger{background:transparent;color:var(--bad);border-color:#e0a89e}',
  '.button:disabled,.button.disabled{cursor:not-allowed;background:#dbdad3;border-color:#dbdad3;color:#8f8e87}',
  '.pitch-grid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}',
  '.pitch{padding:24px 24px 26px 0}',
  '.pitch+.pitch{padding-left:24px;border-left:1px solid var(--line)}',
  '.pitch h2,.pitch h3{margin:8px 0 7px;font-size:18px}',
  '.pitch p{margin:0;color:var(--mut);font-size:14px}',
  '.fact-list li:before{content:"•";margin-right:9px;color:var(--accent)}',
  '.lp{display:flex;flex-direction:column;gap:30px;padding:12px 0 6px}',
  '.lp .pitch{padding:13px 22px 15px 0}',
  '.lp .pitch p{margin-top:6px;font-size:13.5px}',
  '@media(max-width:860px){.lp{gap:22px}.lp .pitch,.lp .pitch+.pitch{padding:12px 0}.hero h1 span{white-space:normal}}',
  '.page-head{display:flex;align-items:end;justify-content:space-between;gap:22px;margin-bottom:22px}',
  '.page-head h1{margin:5px 0 0;font-size:clamp(34px,5vw,58px);line-height:1;letter-spacing:-.04em}',
  '.page-head p{margin:7px 0 0;color:var(--mut);max-width:620px}',
  '.grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(300px,.75fr);gap:22px;align-items:start}',
  '.stack{display:grid;gap:16px}',
  '.card{background:var(--card);border:1px solid var(--line);border-radius:17px;box-shadow:0 12px 36px rgba(52,50,42,.07);padding:22px}',
  '.card.flat{box-shadow:none}',
  '.card-head{display:flex;align-items:start;justify-content:space-between;gap:16px;margin-bottom:18px}',
  '.card h2,.card h3{margin:0;letter-spacing:-.02em}',
  '.card h2{font-size:22px}.card h3{font-size:16px}',
  '.muted{color:var(--mut)}',
  '.empty{padding:26px 0;color:var(--mut);font-size:14px;text-align:center}',
  '.field{margin:0 0 15px}',
  '.label{display:block;margin:0 0 7px;font:700 11px var(--mono);letter-spacing:.08em;text-transform:lowercase;color:var(--mut)}',
  '.input{display:block;width:100%;min-height:44px;padding:10px 13px;border:1.5px solid var(--line);border-radius:11px;background:#fff;color:var(--ink);outline:none}',
  'textarea.input{min-height:112px;resize:vertical;line-height:1.45}',
  '.input:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(255,79,0,.13)}',
  '.help{margin:6px 0 0;color:var(--mut);font-size:12.5px}',
  '.notice{margin:0 0 18px;padding:11px 13px;border-left:2px solid var(--accent);background:rgba(255,79,0,.06);font:500 12px/1.55 var(--mono)}',
  '.notice.error{border-color:var(--bad);background:rgba(209,68,43,.07);color:#7f2c1e}',
  '.notice.success{border-color:var(--ok);background:rgba(26,158,80,.07);color:#126b38}',
  '.vendor-row{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:15px}',
  '.vendor{position:relative;display:flex;align-items:center;justify-content:space-between;min-height:54px;padding:0 14px;border:1.5px solid var(--line);border-radius:11px;font-weight:750}',
  '.vendor.active{border-color:var(--accent);background:var(--soft)}',
  '.vendor.disabled{color:var(--dim);background:#f6f5f1}',
  '.tag{display:inline-flex;padding:3px 7px;border-radius:999px;background:#ecebe6;color:var(--mut);font:700 9px var(--mono);letter-spacing:.05em;text-transform:lowercase}',
  '.composer-actions{display:flex;align-items:center;justify-content:space-between;gap:14px}',
  '.composer-actions .help{margin:0;max-width:460px}',
  '.sess-head{display:flex;justify-content:space-between;align-items:baseline;margin:20px 0 4px}',
  '.sess-head.first{margin-top:0}',
  '.sess-row{display:grid;grid-template-columns:112px minmax(0,1.05fr) minmax(0,.95fr) max-content;column-gap:12px;padding:14px 0;border-top:1px solid #e4e2dc;align-items:center}',
  '.sess-state{display:flex;align-items:center;gap:8px;font:700 10px var(--mono);letter-spacing:.09em;text-transform:lowercase;color:var(--mut);white-space:nowrap}',
  '.sess-dot{width:7px;height:7px;border-radius:50%;flex:none}',
  '.sess-dot.working{background:var(--accent);animation:sess-pulse 1.6s ease-in-out infinite}',
  '.sess-dot.quiet{background:transparent;border:1.5px solid var(--accent)}',
  '.sess-dot.done{background:var(--ink)}',
  '.sess-dot.ended{background:transparent;border:1.5px solid var(--dim)}',
  '.sess-dot.untracked{background:var(--dim)}',
  '@keyframes sess-pulse{0%,100%{opacity:1}50%{opacity:.35}}',
  '.sess-group{font:700 10.5px var(--mono);letter-spacing:.05em;text-transform:lowercase;color:var(--mut)}',
  '.sess-task{font-size:14px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.sess-signal{min-width:0;font:12px/1.5 var(--mono);color:var(--mut)}',
  '.sess-signal .line{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.sess-signal .when{font-size:9.5px;letter-spacing:.07em;text-transform:uppercase;color:var(--dim)}',
  '.sess-actions{display:flex;align-items:center;gap:12px;justify-content:flex-end;white-space:nowrap}',
  '.ghost-btn{background:none;border:0;padding:0;cursor:pointer;font:700 11px var(--mono);letter-spacing:.05em;text-transform:lowercase;color:var(--mut)}',
  '.ghost-btn:hover{color:var(--accent)}',
  '.sess-nolink{font:700 10px var(--mono);letter-spacing:.05em;text-transform:lowercase;color:var(--dim)}',
  '.sess-toggle{display:block;margin-top:16px;text-align:center;font:700 10.5px var(--mono);letter-spacing:.06em;text-transform:lowercase;color:var(--dim);text-decoration:none}',
  '.sess-toggle:hover{color:var(--mut)}',
  '.sess-nudge{margin:-4px 0 0;font:700 10.5px var(--mono);letter-spacing:.06em;text-transform:lowercase;color:var(--dim);text-align:center}',
  '.sess-nudge a{color:var(--mut)}',
  '.sess-nudge a:hover{color:var(--accent)}',
  '.keyline{display:block;margin:14px 0;padding:12px 14px;border:1.5px solid var(--line);border-radius:11px;background:#fff;font:600 13px var(--mono);user-select:all;overflow-x:auto;white-space:nowrap}',
  '.recipe{margin:14px 0 0;padding-left:20px;display:grid;gap:8px;font-size:14px}',
  '.recipe code{font:600 12px var(--mono);background:#ecebe6;padding:1px 5px;border-radius:5px}',
  '.keyblock{display:block;margin:10px 0 4px;padding:12px 14px;border:1.5px solid var(--line);border-radius:11px;background:#fff;font:500 11.5px/1.5 var(--mono);white-space:pre-wrap;overflow-wrap:anywhere;max-width:100%;user-select:all}',
  '.recipe li{min-width:0}',
  '.copywrap{display:block;position:relative}',
  '.copywrap .keyline,.copywrap .keyblock{padding-right:44px}',
  '.copy-btn{position:absolute;top:8px;right:8px;display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;padding:0;border:1.5px solid var(--line);border-radius:8px;background:#fff;color:var(--mut);cursor:pointer}',
  '.copy-btn:hover{border-color:var(--accent);color:var(--accent)}',
  '.copy-btn.copied{border-color:var(--ok);color:var(--ok)}',
  '@media(max-width:720px){.sess-row{grid-template-columns:96px minmax(0,1fr)}.sess-signal{grid-column:2}.sess-actions{grid-column:1 / -1;justify-content:flex-start}}',
  '.prompt{margin:4px 0 6px;font-size:14px;overflow-wrap:anywhere}',
  '.meta{display:flex;flex-wrap:wrap;gap:9px;color:var(--mut);font:600 10.5px var(--mono)}',
  '.set-card{display:grid;gap:14px}',
  '.set-title{display:flex;justify-content:space-between;gap:15px;align-items:start}',
  '.repo-name{font:600 12px var(--mono);color:var(--mut);overflow-wrap:anywhere}',
  '.member-list{display:flex;flex-wrap:wrap;gap:7px}',
  '.member{padding:5px 8px;border:1px solid #deddd7;border-radius:7px;background:#faf9f6;font:600 10.5px var(--mono)}',
  '.toggle-row{display:flex;align-items:start;gap:9px;padding-top:12px;border-top:1px solid #e4e2dc}',
  '.toggle-row input{margin-top:3px;accent-color:var(--accent)}',
  '.toggle-row label{font-size:12.5px;color:var(--mut)}',
  '.prs{display:grid;gap:8px}',
  '.pr{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:start;padding:9px 0;border-top:1px solid #eceae5;font-size:12.5px}',
  '.pr:first-child{border-top:0}',
  '.pr a{text-decoration:none}.pr a:hover{color:var(--accent)}',
  '.pr-repo{color:var(--mut);font:600 10px var(--mono)}',
  '.repo-search{margin-bottom:12px}',
  '.owner-hint{min-height:19px;margin:0 0 9px;padding:0 2px;color:var(--mut);font:600 11px/1.5 var(--mono)}',
  '.owner-hint[hidden]{visibility:hidden}',
  '.repo-picker{display:grid;gap:14px;max-height:440px;overflow:auto;padding-right:3px}',
  '.repo-owner-group{display:grid;gap:7px;transition:opacity .15s ease}',
  '.repo-owner-group.is-dimmed{opacity:.48}',
  '.repo-owner-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 3px;color:var(--mut);font:700 10.5px var(--mono);letter-spacing:.04em;text-transform:lowercase}',
  '.repo-owner-head strong{color:var(--ink);font-size:11.5px}',
  '.repo-owner-rows{display:grid;gap:7px}',
  '.repo-choice{display:grid;grid-template-columns:auto minmax(0,1fr) minmax(120px,.42fr);gap:10px;align-items:center;padding:11px;border:1px solid #deddd7;border-radius:11px;background:#faf9f6}',
  '.repo-choice:hover{border-color:#b9b7ae}',
  '.repo-choice input[type=checkbox]{accent-color:var(--accent)}',
  '.repo-choice strong{font-size:13px;overflow-wrap:anywhere}',
  '.branch-wrap{display:grid;gap:3px;min-width:0}',
  '.branch{min-height:34px;padding:6px 9px;font:600 11px var(--mono)}',
  '.branch-status{min-height:14px;color:var(--mut);font:600 9.5px/1.35 var(--mono)}',
  '.branch-status:empty{display:none}',
  '.branch-status.error{color:var(--bad)}',
  '.repo-owner-group[hidden],.repo-choice[hidden],#repo-no-matches[hidden]{display:none}',
  '.tabs{display:flex;gap:8px;margin-bottom:18px}',
  '.tab{padding:7px 11px;border:1px solid var(--line);border-radius:999px;font:700 11px var(--mono);text-decoration:none;color:var(--mut)}',
  '.tab.active{border-color:var(--accent);background:var(--soft);color:var(--ink)}',
  '.settings-row{display:grid;grid-template-columns:minmax(180px,.4fr) minmax(0,1fr);gap:24px;padding:18px 0;border-top:1px solid #e4e2dc}',
  '.settings-row:first-child{border-top:0;padding-top:0}',
  '.settings-row:last-child{padding-bottom:0}',
  '.settings-row h3{font-size:14px}',
  '.settings-row p{margin:5px 0 0;color:var(--mut);font-size:12.5px}',
  '.code{font:600 12px var(--mono);overflow-wrap:anywhere}',
  '.admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:start}',
  '.admin-wide{grid-column:1/-1}',
  '.metric-row{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:18px}',
  '.metric{display:grid;gap:3px;min-width:118px;padding:12px 14px;border:1px solid #deddd7;border-radius:11px;background:#faf9f6}',
  '.card>.metric{margin-bottom:18px}',
  '.metric-row .metric{margin-bottom:0}',
  '.metric strong{font:800 25px var(--mono);letter-spacing:-.04em}',
  '.admin-split{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(240px,.65fr);gap:22px}',
  '.admin-split h3,.admin-grid>.card>h3{margin:0 0 10px;font-size:13px}',
  '.table-wrap{max-width:100%;overflow:auto;border:1px solid #deddd7;border-radius:11px}',
  '.admin-table{width:100%;border-collapse:collapse;background:#fff;font:600 11px/1.4 var(--mono)}',
  '.admin-table th,.admin-table td{padding:9px 10px;border-bottom:1px solid #eceae5;text-align:left;vertical-align:top;overflow-wrap:anywhere}',
  '.admin-table th{background:#faf9f6;color:var(--mut);font-size:9.5px;letter-spacing:.06em;text-transform:lowercase;white-space:nowrap}',
  '.admin-table tr:last-child td{border-bottom:0}',
  '.admin-empty{color:var(--mut);text-align:center!important}',
  '.daily-table td:first-child,.daily-table td:last-child{white-space:nowrap}',
  '.text-bar{color:var(--accent);letter-spacing:-.08em;white-space:nowrap}',
  '.foot{display:flex;justify-content:space-between;gap:20px;margin-top:50px;padding-top:18px;border-top:1px solid var(--line);color:var(--mut);font:700 10px var(--mono)}',
  '.foot span:last-child{max-width:860px;text-align:right}',
  '@media(max-width:860px){.hero,.grid,.admin-grid,.admin-split{grid-template-columns:1fr}.admin-wide{grid-column:auto}.hero{gap:24px}.pitch-grid{grid-template-columns:1fr}.pitch,.pitch+.pitch{padding:20px 0;border-left:0;border-top:1px solid var(--line)}.pitch:first-child{border-top:0}.repo-choice{grid-template-columns:auto minmax(0,1fr)}.repo-choice .branch-wrap{grid-column:2}.settings-row{grid-template-columns:1fr;gap:10px}}',
  '@media(max-width:620px){.shell{width:min(100% - 24px,1180px);padding-top:12px}.nav{align-items:flex-start;margin-bottom:26px}.nav-left,.nav-right{gap:11px;flex-wrap:wrap}.nav-left .nav-link{display:none}.account span{display:none}.page-head{align-items:start;flex-direction:column}.card{padding:17px}.vendor-row{grid-template-columns:1fr}.composer-actions{align-items:stretch;flex-direction:column}.hero h1{font-size:clamp(34px,9.5vw,48px)}.foot{flex-direction:column}.foot span:last-child{text-align:left}.repo-choice{grid-template-columns:auto minmax(0,1fr)}}',
  '@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}',
].join('')

function csrfField(token) {
  return '<input type="hidden" name="csrf" value="' + escapeHtml(token || '') + '">'
}

export function page(options) {
  const user = options.user
  const csrf = options.csrf || ''
  const nav = user
    ? [
        '<header class="nav"><div class="nav-left">',
        '<a class="wordmark" href="/">blitzos</a>',
        '<a class="nav-link" href="/">feed</a>',
        '<a class="nav-link" href="/repo-sets/new">new context repo</a>',
        '<a class="nav-link" href="/settings">settings</a>',
        '</div><div class="nav-right"><div class="account">',
        user.avatar ? '<img class="avatar" src="' + escapeHtml(user.avatar) + '" alt="">' : '',
        '<span>@' + escapeHtml(user.login) + '</span></div>',
        '<form class="bare-form" method="post" action="/auth/logout">' + csrfField(csrf) + '<button class="link-button" type="submit">sign out</button></form>',
        '</div></header>',
      ].join('')
    : [
        '<header class="nav"><div class="nav-left"><a class="wordmark" href="/">blitzos</a></div>',
        '<div class="nav-right">',
        '<span class="micro status">portal v0</span></div></header>',
      ].join('')
  const footer = '<footer class="foot"><span>BlitzOS portal v0</span><span>' + escapeHtml(PRIVACY_LINE) + '</span></footer>'
  return [
    '<!doctype html><html lang="en"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">',
    '<meta name="theme-color" content="#f2f1ec"><meta name="color-scheme" content="light">',
    '<title>' + escapeHtml(options.title || 'BlitzOS') + '</title>',
    '<meta name="description" content="' + escapeHtml(options.description || 'BlitzOS cloud agents that boot knowing your company.') + '">',
    '<style>' + GLOBAL_CSS + '</style></head><body><main class="shell">',
    nav,
    options.body || '',
    footer,
    '</main></body></html>',
  ].join('')
}

export function hiddenCsrf(token) {
  return csrfField(token)
}
