/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/control-plane/wrangler.toml --include-runtime=false packages/control-plane/worker-configuration.d.ts` (hash: 3e7a8b6fc3d243f462ad16a268305705)
interface __BaseEnv_Env {
	BOX_IMAGES: R2Bucket;
	DB: D1Database;
	BOX_IMAGE_REF: "https://blitz-control-plane.blitzapp.workers.dev/box-image/manifest.json";
	BOX_IMAGE_TAG: "blitz-box:amd64";
	BOX_IMAGE_SHA256: "29a63905864b5b34933df2a2f31a84166d5aff7edfacf9efbc144635b3ff9ea3";
	SESSION_TTL_DAYS: "30";
	MAX_CONCURRENT_WORKSPACES: "10";
	MICROVM_HOSTS: "[{\"name\":\"lab\",\"url\":\"https://behavior-deal-anthony-jobs.trycloudflare.com\",\"tokenVar\":\"MICROVM_LAB_TOKEN\"}]";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BOX_IMAGE_REF" | "BOX_IMAGE_TAG" | "BOX_IMAGE_SHA256" | "SESSION_TTL_DAYS" | "MAX_CONCURRENT_WORKSPACES" | "MICROVM_HOSTS">> {}
}
