/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/control-plane/wrangler.toml --include-runtime=false packages/control-plane/worker-configuration.d.ts` (hash: cd0ea7d846ae378311b886192d7d968b)
interface __BaseEnv_Env {
	BOX_IMAGES: R2Bucket;
	DB: D1Database;
	APP_URL: "https://blitz-control-plane.blitzapp.workers.dev";
	BOX_IMAGE_REF: "https://blitz-control-plane.blitzapp.workers.dev/box-image/manifest.json";
	BOX_IMAGE_TAG: "blitz-box:20260816a-amd64";
	BOX_IMAGE_SHA256: "91f7fb952771c1b3e3b29038e7e8d2c0bcf532f8c3897a46351345a1d77fac5e";
	SESSION_TTL_DAYS: "30";
	MAX_CONCURRENT_WORKSPACES: "10";
	MICROVM_HOSTS: "[{\"name\":\"lab\",\"tokenVar\":\"MICROVM_LAB_TOKEN\",\"dynamic\":true}]";
	CLOUDFLARE_ACCOUNT_ID: "d25a778b256fb6ef6eea554d77c40f27";
	CLOUDFLARE_ZONE_ID: "52fcb3a8adc81b791ea918d3bde25a39";
	WORKSPACE_SURFACE_ZONE: "blitzos.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "BOX_IMAGE_REF" | "BOX_IMAGE_TAG" | "BOX_IMAGE_SHA256" | "SESSION_TTL_DAYS" | "MAX_CONCURRENT_WORKSPACES" | "MICROVM_HOSTS" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_ZONE_ID" | "WORKSPACE_SURFACE_ZONE">> {}
}
