/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: 12943b9acd108cb709e060a6fccf8623)
interface __BaseEnv_Env {
	BOX_IMAGES: R2Bucket;
	DB: D1Database;
	APP_URL: "https://blitz-control-plane.blitzapp.workers.dev";
	BOX_IMAGE_REF: "https://blitz-control-plane.blitzapp.workers.dev/box-image/manifest.json";
	BOX_IMAGE_TAG: "blitz-box:20260818a-amd64";
	BOX_IMAGE_SHA256: "df64957ae502a6b903ac73808e9d0c2cdf4c7a5c67265c62daf95e1b7c1af3bd";
	SESSION_TTL_DAYS: "30";
	MAX_CONCURRENT_WORKSPACES: "10";
	MICROVM_HOSTS: "[{\"name\":\"lab\",\"tokenVar\":\"MICROVM_LAB_TOKEN\",\"dynamic\":true}]";
	CLOUDFLARE_ACCOUNT_ID: "d25a778b256fb6ef6eea554d77c40f27";
	CLOUDFLARE_ZONE_ID: "52fcb3a8adc81b791ea918d3bde25a39";
	WORKSPACE_TUNNEL_ZONE: "blitzos.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "BOX_IMAGE_REF" | "BOX_IMAGE_TAG" | "BOX_IMAGE_SHA256" | "SESSION_TTL_DAYS" | "MAX_CONCURRENT_WORKSPACES" | "MICROVM_HOSTS" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_ZONE_ID" | "WORKSPACE_TUNNEL_ZONE">> {}
}
