/** AWS Signature Version 4 for query-protocol (form-encoded POST) requests.
 *
 * Hand-rolled on Web Crypto because control-plane core may not import npm
 * packages: `test/core-imports.test.ts` pins the module set and asserts every
 * import specifier is relative, and the managed Worker source generated by
 * `scripts/lib/worker-source.mjs` ships `core/` without a node_modules tree.
 * Keeping it here — rather than inside the provider — is what lets
 * `test/aws-sigv4.test.ts` check it against the published AWS SigV4 test-suite
 * vectors instead of against our own output.
 */

const ALGORITHM = "AWS4-HMAC-SHA256";
const REQUEST_TERMINATOR = "aws4_request";
/** The query protocol's content type, exactly as the published AWS SigV4
 * test-suite `post-x-www-form-urlencoded` vector signs it. No charset suffix:
 * the encoded body is pure ASCII (see encodeAwsQueryComponent). */
const FORM_CONTENT_TYPE = "application/x-www-form-urlencoded";

export interface AwsCredentials {
  readonly accessKeyId: string;
  readonly secretAccessKey: string;
  /** Present only for temporary (STS) credentials. */
  readonly sessionToken?: string;
}

/** Ordered name/value pairs. The query protocol repeats names with indexed
 * suffixes (`Tag.1.Key`), so a map would lose the ordering the body needs. */
export type AwsQueryParameters = readonly (readonly [string, string])[];

export interface AwsQueryRequest {
  readonly credentials: AwsCredentials;
  readonly region: string;
  readonly service: string;
  readonly host: string;
  readonly parameters: AwsQueryParameters;
  readonly signedAt: Date;
}

export interface SignedAwsRequest {
  readonly url: string;
  readonly body: string;
  readonly headers: [string, string][];
}

function toHex(buffer: ArrayBuffer): string {
  let hex = "";
  for (const byte of new Uint8Array(buffer)) hex += byte.toString(16).padStart(2, "0");
  return hex;
}

async function sha256Hex(value: string): Promise<string> {
  return toHex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)));
}

async function hmacSha256(key: BufferSource, message: string): Promise<ArrayBuffer> {
  const signingKey = await crypto.subtle.importKey(
    "raw",
    key,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  return crypto.subtle.sign("HMAC", signingKey, new TextEncoder().encode(message));
}

/** RFC 3986 percent-encoding. `encodeURIComponent` leaves `!'()*` alone, and
 * AWS rejects the signature when those survive unescaped. */
export function encodeAwsQueryComponent(value: string): string {
  return encodeURIComponent(value).replace(
    /[!'()*]/gu,
    (character) => `%${character.charCodeAt(0).toString(16).toUpperCase()}`,
  );
}

export function encodeAwsQueryBody(parameters: AwsQueryParameters): string {
  return parameters
    .map(([name, value]) => `${encodeAwsQueryComponent(name)}=${encodeAwsQueryComponent(value)}`)
    .join("&");
}

/** `20260818T134500Z` — the basic-format ISO 8601 stamp SigV4 requires. */
export function amzDateStamp(signedAt: Date): string {
  return `${signedAt.toISOString().replace(/[-:]/gu, "").slice(0, 15)}Z`;
}

async function signingKey(
  secretAccessKey: string,
  date: string,
  region: string,
  service: string,
): Promise<ArrayBuffer> {
  const encoder = new TextEncoder();
  const keyDate = await hmacSha256(encoder.encode(`AWS4${secretAccessKey}`), date);
  const keyRegion = await hmacSha256(keyDate, region);
  const keyService = await hmacSha256(keyRegion, service);
  return hmacSha256(keyService, REQUEST_TERMINATOR);
}

/** Signs a query-protocol POST. The path is always `/` and the query string is
 * always empty for this protocol, so the canonical request is fully determined
 * by the headers and the form body. */
export async function signAwsQueryRequest(
  request: AwsQueryRequest,
): Promise<SignedAwsRequest> {
  const body = encodeAwsQueryBody(request.parameters);
  const amzDate = amzDateStamp(request.signedAt);
  const date = amzDate.slice(0, 8);
  const sessionToken = request.credentials.sessionToken ?? "";
  const canonicalHeaders = sessionToken === ""
    ? `content-type:${FORM_CONTENT_TYPE}\nhost:${request.host}\nx-amz-date:${amzDate}\n`
    : `content-type:${FORM_CONTENT_TYPE}\nhost:${request.host}\nx-amz-date:${amzDate}\nx-amz-security-token:${sessionToken}\n`;
  const signedHeaders = sessionToken === ""
    ? "content-type;host;x-amz-date"
    : "content-type;host;x-amz-date;x-amz-security-token";
  const canonicalRequest = [
    "POST",
    "/",
    "",
    canonicalHeaders,
    signedHeaders,
    await sha256Hex(body),
  ].join("\n");
  const scope = `${date}/${request.region}/${request.service}/${REQUEST_TERMINATOR}`;
  const stringToSign = [
    ALGORITHM,
    amzDate,
    scope,
    await sha256Hex(canonicalRequest),
  ].join("\n");
  const signature = toHex(
    await hmacSha256(
      await signingKey(request.credentials.secretAccessKey, date, request.region, request.service),
      stringToSign,
    ),
  );
  const headers: [string, string][] = [
    ["content-type", FORM_CONTENT_TYPE],
    ["x-amz-date", amzDate],
    [
      "authorization",
      `${ALGORITHM} Credential=${request.credentials.accessKeyId}/${scope},`
        + ` SignedHeaders=${signedHeaders}, Signature=${signature}`,
    ],
  ];
  if (sessionToken !== "") headers.push(["x-amz-security-token", sessionToken]);
  return { url: `https://${request.host}/`, body, headers };
}
